spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 150
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

#    sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/data_prod.sql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
#    defer-datasource-initialization: true
#    open-in-view: false

  data:
    mongodb:
      uri: ${MONGODB_URL}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

    redis:
      port: 6379
      host: ${REDIS_HOST}
logging:
  level:
    org.springframework.security: DEBUG
    com.youniform.api: INFO