spring:
  application:
    name: api
  config:
    import:
      - classpath:jwt.yml
  profiles:
    active: ${PROFILE}

  data:
    redis:
      port: 8379
      host: localhost

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_SECRETKEY}
