spring:
  application:
    name: api

  data:
    redis:
      port: 6379
      host: localhost

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:youniform
    username: sa
    password: ssafy

  h2:
    console:
      enabled: true
      path: /h2-console